from django import forms
from .models import Dataset
from django_select2.forms import Select2MultipleWidget, Select2Widget

CATEGORY_CHOICES = (
    ('Accounting', 'Accounting'),
    ('Administration', 'Administration'),
    ('Advertising', 'Advertising'),
    ('Aerospace', 'Aerospace'),
    ('Agriculture', 'Agriculture'),
    ('Architecture', 'Architecture'),
    ('Arts and Entertainment', 'Arts and Entertainment'),
    ('Automotive', 'Automotive'),
    ('Aviation', 'Aviation'),
    ('Banking', 'Banking'),
    ('Biotechnology', 'Biotechnology'),
    ('Business Development', 'Business Development'),
    ('Business Services', 'Business Services'),
    ('Chemicals', 'Chemicals'),
    ('Clean Energy', 'Clean Energy'),
    ('Computer Hardware', 'Computer Hardware'),
    ('Computer Software', 'Computer Software'),
    ('Construction', 'Construction'),
    ('Consulting', 'Consulting'),
    ('Consumer Goods', 'Consumer Goods'),
    ('Defense', 'Defense'),
    ('Design', 'Design'),
    ('Education', 'Education'),
    ('Electronics', 'Electronics'),
    ('Energy', 'Energy'),
    ('Engineering', 'Engineering'),
    ('Environmental Services', 'Environmental Services'),
    ('Finance', 'Finance'),
    ('Food and Beverage', 'Food and Beverage'),
    ('Forestry', 'Forestry'),
    ('Government', 'Government'),
    ('Healthcare', 'Healthcare'),
    ('Hospitality', 'Hospitality'),
    ('Human Resources', 'Human Resources'),
    ('Information Technology', 'Information Technology'),
    ('Insurance', 'Insurance'),
    ('Legal', 'Legal'),
    ('Logistics', 'Logistics'),
    ('Manufacturing', 'Manufacturing'),
    ('Marketing', 'Marketing'),
    ('Media', 'Media'),
    ('Medical', 'Medical'),
    ('Mining', 'Mining'),
    ('Nonprofit', 'Nonprofit'),
    ('Oil and Gas', 'Oil and Gas'),
    ('Pharmaceuticals', 'Pharmaceuticals'),
    ('Professional Services', 'Professional Services'),
    ('Real Estate', 'Real Estate'),
    ('Retail', 'Retail'),
    ('Sales', 'Sales'),
    ('Science and Engineering', 'Science and Engineering'),
    ('Sports', 'Sports'),
    ('Technology', 'Technology'),
    ('Telecommunications', 'Telecommunications'),
    ('Transportation', 'Transportation'),
    ('Travel and Tourism', 'Travel and Tourism'),
    ('Utilities', 'Utilities'),
    ('Wholesale', 'Wholesale'),
    ('Other', 'Other'),
)

DATA_TYPE_CHOICES = (
    ("Audio", "Audio"),
    ("Bigquery", "Bigquery"),
    ("Categorical", "Categorical"),
    ("Graph", "Graph"),
    ("Image", "Image"),
    ("Multimodal", "Multimodal"),
    ("Tabular", "Tabular"),
    ("Text", "Text"),
    ("Video", "Video"),
)